// Define action types
export const CHOOSE_WEBSITE = 'CHOOSE_WEBSITE';
export const GET_PROVIDER_GROUP_NAME="GET_PROVIDER_GROUP_NAME"
export const SET_ACTIVE_SIDEBAR_OPTION="SET_ACTIVE_SIDEBAR_OPTION"
export const SET_COUPON_CODE="SET_COUPON_CODE"
export const SET_LOGIN_FORM="SET_LOGIN_FORM"




